build_from:
  amd64: "ghcr.io/hassio-addons/base:15.0.7"
  aarch64: "ghcr.io/hassio-addons/base:15.0.7"
  armv7: "ghcr.io/hassio-addons/base:15.0.7"
labels:
  io.hass.version: "1.0.0"
  io.hass.type: "addon"
  io.hass.arch: "amd64|aarch64|armv7"
args:
  BUILD_ARCH: "{arch}"
  BUILD_DATE: "{build_date}"
  BUILD_DESCRIPTION: "Plant tracking system with automation and Home Assistant integration"
  BUILD_NAME: "GrowFlow Plant Tracker"
  BUILD_REF: "{build_ref}"
  BUILD_REPOSITORY: "https://github.com/moritzheine/growflow"
  BUILD_VERSION: "{build_version}"