name: GrowFlow Cannabis Tracker
version: "1.0.0"
slug: growflow
description: Cannabis Plant Tracker with automation and Home Assistant integration
url: https://github.com/yourusername/growflow
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: GrowFlow Web Interface
webui: http://[HOST]:[PORT:8080]
ingress: true
ingress_port: 8080
panel_icon: mdi:cannabis
panel_title: GrowFlow
hassio_api: true
hassio_role: default
auth_api: true
homeassistant_api: true
map:
  - config:rw
  - share:rw
options:
  mqtt_broker: core-mosquitto
  mqtt_port: 1883
  ha_url: http://supervisor/core
  log_level: info
  backup_enabled: true
  backup_interval_hours: 24
schema:
  mqtt_broker: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  ha_url: url
  ha_token: password?
  log_level: list(debug|info|warning|error)?
  backup_enabled: bool?
  backup_interval_hours: int(1,168)?